### ISSUE TITLE
Twitter連携ログインについて

### ISSUE THREAD

**Issue by ayuoh** [ayuoh/ws-reviews#9]
Twitter連携ログインを実装しようとしています。

## ■現状
Twitter Developerの設定などは済んでいて、認証画面までは出ている状態です。
（Twitter Developerは無料で使用しています。）
![image](https://github.com/ayuoh/ws-reviews/assets/113239257/74917cbe-88cf-402d-b048-27682c7c3015)

**Authorize appを押してもこの画面に戻ってきてしまいます。**
ログを見るとリダイレクトが起こってこの画面に戻ってきているようです。

```
22:46:11 web.1  | Started GET "/oauth/twitter/callback" for 127.0.0.1 at 2023-12-19 22:46:11 +0900
22:46:11 web.1  | Processing by OauthsController#oauth as HTML
22:46:11 web.1  | Started GET "/oauth/twitter/callback" for 127.0.0.1 at 2023-12-19 22:46:11 +0900
22:46:11 web.1  | Started GET "/oauth/twitter/callback" for 127.0.0.1 at 2023-12-19 22:46:11 +0900
22:46:11 web.1  | Processing by OauthsController#oauth as HTML
22:46:11 web.1  |   Parameters: {"provider"=>"twitter"}
22:46:11 web.1  | Redirected to https://api.twitter.com/oauth/authenticate?oauth_callback=http%3A%2F%2F127.0.0.1%3A3000%2Foauth%2Ftwitter%2Fcallback%3Fprovider%3Dtwitter&oauth_token=YiG1ZgAAAAABqSqYAAABjIJTuIY
22:46:11 web.1  | Completed 302 Found in 811ms (ActiveRecord: 0.0ms | Allocations: 5737)
22:46:11 web.1  |
22:46:11 web.1  |
22:46:12 web.1  | Started GET "/oauth/twitter/callback" for 127.0.0.1 at 2023-12-19 22:46:12 +0900
22:46:12 web.1  | Processing by OauthsController#oauth as HTML
22:46:12 web.1  |   Parameters: {"provider"=>"twitter"}
22:46:12 web.1  | Redirected to https://api.twitter.com/oauth/authenticate?oauth_callback=http%3A%2F%2F127.0.0.1%3A3000%2Foauth%2Ftwitter%2Fcallback%3Fprovider%3Dtwitter&oauth_token=5qEdRgAAAAABqSqYAAABjIJTuv4
22:46:12 web.1  | Completed 302 Found in 209ms (ActiveRecord: 0.0ms | Allocations: 4829)
22:46:12 web.1  |
22:46:12 web.1  |
22:46:16 web.1  | Started GET "/oauth/twitter/callback?provider=twitter&oauth_token=[FILTERED]&oauth_verifier=y2bNSdsBen0bHfrhQQgXGiuCss86d59I" for 127.0.0.1 at 2023-12-19 22:46:16 +0900
22:46:16 web.1  | Processing by OauthsController#oauth as HTML
22:46:16 web.1  |   Parameters: {"provider"=>"twitter", "oauth_token"=>"[FILTERED]", "oauth_verifier"=>"y2bNSdsBen0bHfrhQQgXGiuCss86d59I"}
22:46:16 web.1  | Redirected to https://api.twitter.com/oauth/authenticate?oauth_callback=http%3A%2F%2F127.0.0.1%3A3000%2Foauth%2Ftwitter%2Fcallback%3Fprovider%3Dtwitter&oauth_token=QWc_GQAAAAABqSqYAAABjIJTy78
22:46:16 web.1  | Completed 302 Found in 278ms (ActiveRecord: 0.0ms | Allocations: 4829)
22:46:16 web.1  |
22:46:16 web.1  |

```

twitterの方を見てみると連携はできているようです。
![IMG_0089](https://github.com/ayuoh/ws-reviews/assets/113239257/fbedc571-f269-454e-bf84-e604e38fbaff)

## ■やりたいこと
この画面からAuthorize appを押したら、自作アプリの画面の方に戻りたいです。

## ■調べた・考えたこと
コード302でエラーということで、一時的なリダイレクトという感じで戻ってきているのかなと思います。

ここからは調べられなかったので憶測になります。

ログインにはsorceryを使用していて、以下の記事を参考にして実装しました。
https://github.com/Sorcery/sorcery/wiki/External
https://qiita.com/zakirun/items/da012e6d8f7282c3c912

Twitter APIが変更になったタイミングでsorceryが対応できなくなりエラーのURLにアクセス→302リダイレクトが起きているのかもと思いました。

## ■助けていただきたいこと
Twitterアカウントと連携まではできているようなので、認証画面から自作のアプリに画面を遷移させるために何かいい方法はご存知ありませんでしょうか？

Tiwtterでログインできなくてもアカウントと紐付けしたいと考えているので、
紐付けだけでもできるような方法はありますでしょうか？

一応無料でも1アプリだったら認証できるようなので、実装したいのですが、
もし情報不足で実装できないならば仕様を変えようかと思っています……

お忙しいところ恐縮ですが、どうぞよろしくお願いいたします。

**Comment by kenchasonakai** [comment]
コードちゃんと見ないとなんとも言えないって感じですが、OauthsController#oauthでtwitterからレスポンス返ってきた後にまたtwitter側にリクエスト送る感じになったりしてるんですかね？

OauthsController#oauthで自分のアプリのどっかにリダイレクトするように設定したらいけたりしませんかね？

**Comment by ayuoh** [comment]
コメントありがとうございます。
ルーティング周りを確認したところ、パスと呼び出すメソッドの組み合わせが間違っていることがわかりました！
（oauth#oauthとoauth#callbackのルーティングを逆にしていました。）

その後もうまくログインできない不具合がありましたが、
[ふぁらおさんの記事](https://hackmd.io/@SKjw2RY-RNCUNSdJfEWPig/hbkk)見ながら原因を見つけることができました！
ご協力いただきありがとうございました！
